PCB: false
batchsize: 32
color_jitter: false
data_dir: /home/lxwang/MyProjects/first_test_reid/cuhk03_hand/pytorch
droprate: 0.5
erasing_p: 0
fp16: false
gpu_ids: '0'
lr: 0.06
name: ft_ResNet50
stride: 2
train_all: false
use_dense: false
